<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Default email</title>
</head>
<body>
    <div class="header">
        <strong>Happy birthday, ${birthdayFirstName} ${birthdayLastName}</strong>
        <br>
    </div>
    <div class="body">
        <p>${message}</p>
        <br>
    </div>
    <div>
        <p>${firstname} ${lastname}<br>
        ${email}</p>
    </div>
</body>
</html>