USE `contact_db`;

INSERT INTO nationalities(nationality) VALUES
("Afghanistan"),
("Albania"),
("Algeria"),
("Andorra"),
("Angola"),
("Antigua and Barbuda"),
("Argentina"),
("Armenia"),
("Australia"),
("Austria"),
("Azerbaijan"),
("Bahamas"),
("Bahrain"),
("Bangladesh"),
("Barbados"),
("Belarus"),
("Belgium"),
("Belize"),
("Benin"),
("Bhutan"),
("Bolivia"),
("Bosnia and Herzegovina"),
("Botswana"),
("Brazil"),
("Brunei"),
("Bulgaria"),
("Burkina Faso"),
("Burundi"),
("Cabo Verde"),
("Cambodia"),
("Cameroon"),
("Canada"),
("Central African Republic (CAR)"),
("Chad"),
("Chile"),
("China"),
("Colombia"),
("Comoros"),
("Democratic Republic of the Congo"),
("Republic of the Congo"),
("Costa Rica"),
("Cote d'Ivoire"),
("Croatia"),
("Cuba"),
("Cyprus"),
("Czech Republic"),
("Denmark"),
("Djibouti"),
("Dominica"),
("Dominican Republic"),
("Ecuador"),
("Egypt"),
("El Salvador"),
("Equatorial Guinea"),
("Eritrea"),
("Estonia"),
("Ethiopia"),
("Fiji"),
("Finland"),
("France"),
("Gabon"),
("Gambia"),
("Georgia"),
("Germany"),
("Ghana"),
("Greece"),
("Grenada"),
("Guatemala"),
("Guinea"),
("Guinea-Bissau"),
("Guyana"),
("Haiti"),
("Honduras"),
("Hungary"),
("Iceland"),
("India"),
("Indonesia"),
("Iran"),
("Iraq"),
("Ireland"),
("Israel"),
("Italy"),
("Jamaica"),
("Japan"),
("Jordan"),
("Kazakhstan"),
("Kenya"),
("Kiribati"),
("Kosovo"),
("Kuwait"),
("Kyrgyzstan"),
("Laos"),
("Latvia"),
("Lebanon"),
("Lesotho"),
("Liberia"),
("Libya"),
("Liechtenstein"),
("Lithuania"),
("Luxembourg"),
("Macedonia"),
("Madagascar"),
("Malawi"),
("Malaysia"),
("Maldives"),
("Mali"),
("Malta"),
("Marshall Islands"),
("Mauritania"),
("Mauritius"),
("Mexico"),
("Micronesia"),
("Moldova"),
("Monaco"),
("Mongolia"),
("Montenegro"),
("Morocco"),
("Mozambique"),
("Myanmar (Burma)"),
("Namibia"),
("Nauru"),
("Nepal"),
("Netherlands"),
("New Zealand"),
("Nicaragua"),
("Niger"),
("Nigeria"),
("North Korea"),
("Norway"),
("Oman"),
("Pakistan"),
("Palau"),
("Palestine"),
("Panama"),
("Papua New Guinea"),
("Paraguay"),
("Peru"),
("Philippines"),
("Poland"),
("Portugal"),
("Qatar"),
("Romania"),
("Russia"),
("Rwanda"),
("Saint Kitts and Nevis"),
("Saint Lucia"),
("Saint Vincent and the Grenadines"),
("Samoa"),
("San Marino"),
("Sao Tome and Principe"),
("Saudi Arabia"),
("Senegal"),
("Serbia"),
("Seychelles"),
("Sierra Leone"),
("Singapore"),
("Slovakia"),
("Slovenia"),
("Solomon Islands"),
("Somalia"),
("South Africa"),
("South Korea"),
("South Sudan"),
("Spain"),
("Sri Lanka"),
("Sudan"),
("Suriname"),
("Swaziland"),
("Sweden"),
("Switzerland"),
("Syria"),
("Taiwan"),
("Tajikistan"),
("Tanzania"),
("Thailand"),
("Timor-Leste"),
("Togo"),
("Tonga"),
("Trinidad and Tobago"),
("Tunisia"),
("Turkey"),
("Turkmenistan"),
("Tuvalu"),
("Uganda"),
("Ukraine"),
("United Arab Emirates (UAE)"),
("United Kingdom (UK)"),
("United States of America (USA)"),
("Uruguay"),
("Uzbekistan"),
("Vanuatu"),
("Vatican City (Holy See)"),
("Venezuela"),
("Vietnam"),
("Yemen"),
("Zambia"),
("Zimbabwe");

INSERT INTO companies(company) VALUES
("iTechArt"),
("Epam"),
("ITransition");

INSERT INTO photos(photo) VALUES
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL);

INSERT INTO contacts(first_name, surname, patronymic,
	birthday, website, email, country, city, address,
	index_number, gender, marital_status, id_nationality,
	id_company, id_photo) VALUES
("Ivan", "Vasilevskiy", "Aleksandr", "1998-04-07", "www.github.com/Vasilevskiy", "ivan.vasilevskiy@gmail.com", "Belarus", "Soligorsk", "Zheleznay 5/44", "220001", "Male", "Single", 1, 1, 1),
("Alexey", "Fedorov", "Aleksandr", "1998-08-11", "www.github.com/Feodorov", "alexey.fedorov@gmail.com", "Belarus", "Smorgon", "Vileyskaya 90/47", "220022", "Male", "Single", 1, 2, 2),
("Sergey", "Pastushenko", "Aleksandr", "1998-12-07", "www.github.com/Pastushenko", "sergey.pastushenko@gmail.com", "Belarus", "Brest", "Zelenaya 14", "220034", "Male", "Single", 1, 3, 3),
("Ivan", "Vasilevskiy", "Aleksandr", "1998-04-07", "www.github.com/Vasilevskiy", "ivan.vasilevskiy@gmail.com", "Belarus", "Soligorsk", "Zeleznay 5/44", "220001", "Male", "Single", 1, 1, 4),
("Ivan", "Vasilevskiy", "Aleksandr", "1998-04-07", "www.github.com/Vasilevskiy", "ivan.vasilevskiy@gmail.com", "Belarus", "Soligorsk", "Zeleznay 5/44", "220001", "Male", "Single", 1, 1, 5),
("Ivan", "Vasilevskiy", "Aleksandr", "1998-04-07", "www.github.com/Vasilevskiy", "ivan.vasilevskiy@gmail.com", "Belarus", "Soligorsk", "Zeleznay 5/44", "220001", "Male", "Single", 1, 1, 6),
("Ivan", "Vasilevskiy", "Aleksandr", "1998-04-07", "www.github.com/Vasilevskiy", "ivan.vasilevskiy@gmail.com", "Belarus", "Soligorsk", "Zeleznay 5/44", "220001", "Male", "Single", 1, 1, 7),
("Ivan", "Vasilevskiy", "Aleksandr", "1998-04-07", "www.github.com/Vasilevskiy", "ivan.vasilevskiy@gmail.com", "Belarus", "Soligorsk", "Zeleznay 5/44", "220001", "Male", "Single", 1, 1, 8),
("Ivan", "Vasilevskiy", "Aleksandr", "1998-04-07", "www.github.com/Vasilevskiy", "ivan.vasilevskiy@gmail.com", "Belarus", "Soligorsk", "Zeleznay 5/44", "220001", "Male", "Single", 1, 1, 9),
("Ivan", "Vasilevskiy", "Aleksandr", "1998-04-07", "www.github.com/Vasilevskiy", "ivan.vasilevskiy@gmail.com", "Belarus", "Soligorsk", "Zeleznay 5/44", "220001", "Male", "Single", 1, 1, 10);

INSERT INTO phones(id_contact, phone_number, phone_type, commentary)
VALUES
(1, "+375291111111", "Mobile", "comment"),
(1, "+375292222222", "Home", "comment"),
(1, "+375293333333", "Working", "comment");

INSERT INTO attachments(id_contact, name, download_date,
commentary, attachment) VALUES
(1, "file1", "2017-07-01", "comment", NULL),
(1, "file2", "2017-07-02", "comment", NULL),
(1, "file3", "2017-07-03", "comment", NULL);